---
title: "Mathematical Biostatistics Bootcamp 1"
subtitle: "Module 1 Homework"
author: "Dan Killian"
date: "November 2020"
output: 
  html_document:
    toc: true
    toc_depth: '5'
    toc_float: yes
---

####
```{r global_options, echo=F}

# standard figure size and generate clean output
knitr::opts_chunk$set(fig.width=8, fig.height=6, fig.align='center', warning=FALSE, message=FALSE, cache=TRUE, error=T)

```

  
```{r libraries, echo=F}
library(tidyverse)
library(strengejacke)
library(psych)
library(scales)
library(brms)
library(rethinking)
library(rstanarm)
library(rstantools)
library(skimr)
library(knitr)
library(xlsx)
library(here)
library(haven)
library(showtext)
library(gfonts)
```

```{r formatting, echo=F}
# display to three decimal points, scientific notation displays at around six digits
options(digits=3, scipen=6)

# requires showtext package
showtext_auto()

# requires gfonts package
use_pkg_gfont("open-sans")

# graphic style
theme_set(theme_bw() + theme(panel.grid.minor.x=element_blank(),
                             panel.grid.minor.y=element_blank(),
                             plot.title=element_text(face="bold",size=18, hjust=.5, family = "sans"),
                             plot.subtitle = element_text(size=16, family="sans"),
                             plot.caption=element_text(size=12, family="sans"),
                             axis.title=element_text(size=16, family="sans"),
                             axis.text=element_text(size=14, family="sans"),    
                             legend.text=element_text(size=14, family="sans"),
                             strip.text=element_text(size=14, family="sans"))) 

# for single graphs, I have recently come to like borderless
nobord <- theme(panel.border=element_blank(),
                axis.ticks = element_blank())
```

##### 1.

The intersection of B and not A P(B\cap{A}^C) is always equal to?

The intersection of B and not A is all of B that is not in A. P(B) - P(B \cap{A})

##### 2. 

When does P(A \cup{B}) = P(A) + P(B)? Multiple response. 

The union of A and B is A + B when A and B are independent. The language 'mutually exclusive' would also cover independence. P(A \cup{B}) = 0 is also a statement of independence as there is no intersection. 








